#!/bin/sh
chown root:root /etc/init.d/lockss
chmod 0755 /etc/init.d/lockss
chown root:root /etc/lockss
chmod 0755 /etc/lockss
for A in functions hostconfig rundaemon startdaemon runssl
do
	chown root:root /etc/lockss/${A}
	chmod 0755 /etc/lockss/${A}
done
mkdir -p /var/log/lockss
chown lockss:root /var/log/lockss
chmod 0755 /var/log/lockss
if [ -s /etc/lockss/config.dat ]; then /etc/init.d/lockss start ; echo "Started LOCKSS" ; else echo Please run /etc/lockss/hostconfig .  See /etc/lockss/README for details. ; fi
