#! /bin/sh

# PROJECT_DIR
PROJECT_DIR=`( cd ../../..; pwd )`
export PROJECT_DIR

if [ "$1" == "clean" ] ; then
  rm -rf lib
fi

for i in 1 2 3 4 ; do
    cd test$i
    if [ "$1" == "start" ] ; then
	../testrundaemons &
	echo started in `pwd`
    elif [ "$1" == "clean" ] ; then
       rm -rf config
       rm -rf cache
       rm -rf history
       rm -rf localA
       rm -rf plugins
       rm -rf iddb
       rm -rf lib
       rm -f test.out
       rm -f dpid
    else
	kill `cat dpid`
        echo stopped in `pwd`
    fi
    cd ..
done
