#! /bin/bash

# PROJECT_DIR
PROJECT_DIR=`( cd ../../../..; pwd )`
export PROJECT_DIR

for (( i=1 ; i<=4 ; i++ )) ; do
  (
    cd testHW$i
    if [ "$1" == "start" ] ; then
	../testrundaemonsHW &
	echo started in `pwd`
    else
	kill `cat dpid`
        echo stopped in `pwd`
    fi
  )
done
