#! /bin/bash

# "." here is the test<n> dir
PROP_URL_LIST="../../common.txt ../lockss.txt ../lockss.opt local.txt local.opt"

mkdir -p ../lib
cp ${PROJECT_DIR}/lib/lockss.jar ../lib
cp ${PROJECT_DIR}/lib/lockss-test.jar ../lib
CLASSPATH=../lib/lockss.jar:../lib/lockss-test.jar:`cat ${PROJECT_DIR}/test/test-classpath`
export CLASSPATH

echo running in `pwd` at `date`
#echo CLASSPATH=$CLASSPATH
# for large caches, need to pass "-ms4m -mx64m" to java
java -Dorg.lockss.defaultLogLevel=DEBUG RunDaemon ${PROP_URL_LIST} >>test.out 2>&1 &
echo $! >dpid
wait
echo stopped with status $? in `pwd` at `date`
