/*
 * $Id: TaylorAndFrancisPdfFilterFactory.java,v 1.3 2012-07-10 23:56:18 thib_gc Exp $
 */

/*

Copyright (c) 2000-2011 Board of Trustees of Leland Stanford Jr. University,
all rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
STANFORD UNIVERSITY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Except as contained in this notice, the name of Stanford University shall not
be used in advertising or otherwise to promote the sale, use or other dealings
in this Software without prior written authorization from Stanford University.

*/

package org.lockss.plugin.taylorandfrancis;

import java.io.*;

import org.apache.commons.io.*;
import org.lockss.daemon.PluginException;
import org.lockss.plugin.*;
import org.lockss.util.*;
import org.pdfbox.cos.*;
import org.pdfbox.pdfwriter.ContentStreamWriter;
import org.pdfbox.pdmodel.common.PDStream;

@Deprecated
public class TaylorAndFrancisPdfFilterFactory implements FilterFactory {

  public static class FilteringException extends PluginException {
    public FilteringException() { super(); }
    public FilteringException(String msg, Throwable cause) { super(msg, cause); }
    public FilteringException(String msg) { super(msg); }
    public FilteringException(Throwable cause) { super(cause); }
  }

  @Override
  public InputStream createFilteredInputStream(ArchivalUnit au,
                                               InputStream in,
                                               String encoding)
      throws PluginException {
    PdfDocument pdfDocument = null;
    try {
      pdfDocument = new PdfDocument(in);
      
      // Remove the modification date
      pdfDocument.removeCreationDate();
      pdfDocument.removeModificationDate();
      
      // Normalize the trailer ID
      COSDictionary trailer = pdfDocument.getTrailer();
      if (trailer != null) {
        // Put bogus ID to prevent autogenerated (variable) ID
        COSArray id = new COSArray();
        id.add(new COSString("12345678901234567890123456789012"));
        id.add(id.get(0));
        trailer.setItem(COSName.getPDFName("ID"), id);
      }
      
      // Force a rewrite of every page, which PDFBox does deterministically
      for (int i = 0 ; i < pdfDocument.getNumberOfPages() ; ++i) {
        PdfPage pdfPage = pdfDocument.getPage(i);
        PDStream resultStream = pdfPage.getPdfDocument().makePdStream();
        OutputStream outputStream = resultStream.createOutputStream();
        ContentStreamWriter tokenWriter = new ContentStreamWriter(outputStream);
        tokenWriter.writeTokens(pdfPage.getStreamTokens());
        pdfPage.setContents(resultStream);
      }
      
      // Turn file back into an InputStream
      DeferredTempFileOutputStream pdfOutputStream = new DeferredTempFileOutputStream(10*1024*1024 /* aka 10MB */);
      pdfDocument.save(pdfOutputStream);
      if (pdfOutputStream.isInMemory()) {
        return new ByteArrayInputStream(pdfOutputStream.getData());
      }
      else {
        File tempFile = null; 
        try {
          tempFile = pdfOutputStream.getFile();
          return new CloseCallbackInputStream(new FileInputStream(tempFile),
                                              new CloseCallbackInputStream.Callback() {
                                                public void streamClosed(Object file) {
                                                  FileUtils.deleteQuietly(((File)file));
                                                }
                                              },
                                              tempFile);
        }
        catch (FileNotFoundException fnfe) {
          FileUtils.deleteQuietly(tempFile);
          throw fnfe;
        }
      }
    }
    catch (IOException ioe) {
      throw new FilteringException(ioe);
    }
    finally {
      if (pdfDocument != null) {
        pdfDocument.close();
      }
    }
    
  } 
  
}
