#!/bin/sh

if [ ! -d ../clockss ]; then
  echo "You need to create your own tdb/clockss subdirectory."
  exit 1
fi
CLOCKSS=`find ../clockss | wc -l`
if [ "${CLOCKSS}" != "1" ]; then
  echo "Your tdb/clockss subdirectory needs to be empty."
  exit 1
fi
for f in *.tdb ; do
  cat $f | sed -e 's@status ; status2@status1 ; status@' -e 's@hidden\[proxy\]@proxy@' > ../clockss/$f
done
