#!/bin/sh

# Copyright (c) 2000-2023, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

CLOCKSS='../clockss'

if [ ! -d "${CLOCKSS}" ] ; then
  echo "You need to create your own tdb/clockss subdirectory."
  exit 1
fi
if [ "$(find "${CLOCKSS}" | wc -l)" != "1" ] ; then
  echo "Your tdb/clockss subdirectory needs to be empty."
  exit 1
fi
for d in . * ; do
  if [ -d "${d}" ]; then
    if [ "${d}" != '.' ] ; then
      mkdir "${CLOCKSS}/${d}"
    fi
    if [ -x "${d}.sh" ] ; then
      cp -P "${d}.sh" "${CLOCKSS}" # -P is --no-dereference; these scripts are often symlinks
    fi
    for f in ${d}/*.tdb ; do
      sed -e 's@status\( *\);\( *\)status2@status1\1;\2status@' -e 's@hidden\[proxy\]@proxy@' "$f" > "${CLOCKSS}/${f}"
    done
  fi
done
