#!/bin/sh
CLASSPATHFILE=test/run-classpath
if [ ! -f $CLASSPATHFILE ]; then
  echo "${CLASSPATHFILE} not found; run from root of project after ant jar-lockss"
  exit 1
fi
if [ "X${JAVA_HOME}" = "X" ]; then
  JAVA=java
else
  JAVA=$JAVA_HOME/bin/java
fi
$JAVA -Xmx1024m -classpath `cat $CLASSPATHFILE` org.lockss.tdb.TdbXml "$@"
