#! /bin/bash

# PROJECT_DIR
PROJECT_DIR=`( cd ../../..; pwd )`
export PROJECT_DIR

if [ "$1" == "start" ] ; then
    shift
    ./rundaemon "$@" &
    echo daemon started
elif [ "$1" == "clean" ] ; then
    rm -rf cache
    rm -rf history
    rm -rf localA
    rm -rf lib
    rm -f test.out
else
    kill -9 `cat dpid`
    echo daemon stopped
fi
