#! /bin/bash

# PROJECT_DIR
PROJECT_DIR=`( cd ../../..; pwd )`
export PROJECT_DIR

if [ "$1" == "start" ] ; then
    shift
    ./rundaemon "$@" &
    echo daemon started
else
    kill -9 `cat dpid`
    echo daemon stopped
fi
