#! /bin/bash

PROP_URL_LIST="http://props.lockss.org:8001/03042003_dev/lockss.txt local.txt"

# local copy of lockss jars allows recompile while we're running
mkdir -p lib
cp ${PROJECT_DIR}/lib/lockss.jar lib
cp ${PROJECT_DIR}/lib/lockss-test.jar lib
CLASSPATH=lib/lockss.jar:lib/lockss-test.jar:`cat ${PROJECT_DIR}/test/test-classpath`
export CLASSPATH
#echo CLASSPATH=$CLASSPATH
JVM_ARGS="-Xmx70m -Dsun.net.inetaddr.ttl=3600"

echo running at `date`
# for large caches, need to pass "-ms4m -mx64m" to java
java -Dorg.lockss.defaultLogLevel=DEBUG "$@" org.lockss.app.LockssDaemon ${PROP_URL_LIST} >>test.out 2>&1 &
echo $! >dpid
wait
echo stopped with status $? at `date`
