/*
 * LOCKSS Repository Service REST API
 * REST API of the LOCKSS Repository Service
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: lockss-support@lockss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.lockss.laaws.model.rs;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Objects;

/** Artifact */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Artifact implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";

  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_COLLECTION = "collection";

  @SerializedName(SERIALIZED_NAME_COLLECTION)
  private String collection;

  public static final String SERIALIZED_NAME_AUID = "auid";

  @SerializedName(SERIALIZED_NAME_AUID)
  private String auid;

  public static final String SERIALIZED_NAME_URI = "uri";

  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;

  public static final String SERIALIZED_NAME_VERSION = "version";

  @SerializedName(SERIALIZED_NAME_VERSION)
  private Integer version;

  public static final String SERIALIZED_NAME_COMMITTED = "committed";

  @SerializedName(SERIALIZED_NAME_COMMITTED)
  private Boolean committed;

  public static final String SERIALIZED_NAME_STORAGE_URL = "storageUrl";

  @SerializedName(SERIALIZED_NAME_STORAGE_URL)
  private String storageUrl;

  public static final String SERIALIZED_NAME_CONTENT_LENGTH = "contentLength";

  @SerializedName(SERIALIZED_NAME_CONTENT_LENGTH)
  private Integer contentLength;

  public static final String SERIALIZED_NAME_CONTENT_DIGEST = "contentDigest";

  @SerializedName(SERIALIZED_NAME_CONTENT_DIGEST)
  private String contentDigest;

  public static final String SERIALIZED_NAME_COLLECTION_DATE = "collectionDate";

  @SerializedName(SERIALIZED_NAME_COLLECTION_DATE)
  private Long collectionDate;

  public Artifact() {}

  public Artifact id(String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   */
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Artifact collection(String collection) {

    this.collection = collection;
    return this;
  }

  /**
   * Get collection
   *
   * @return collection
   */
  @ApiModelProperty(value = "")
  public String getCollection() {
    return collection;
  }

  public void setCollection(String collection) {
    this.collection = collection;
  }

  public Artifact auid(String auid) {

    this.auid = auid;
    return this;
  }

  /**
   * Get auid
   *
   * @return auid
   */
  @ApiModelProperty(value = "")
  public String getAuid() {
    return auid;
  }

  public void setAuid(String auid) {
    this.auid = auid;
  }

  public Artifact uri(String uri) {

    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   *
   * @return uri
   */
  @ApiModelProperty(value = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public Artifact version(Integer version) {

    this.version = version;
    return this;
  }

  /**
   * Get version
   *
   * @return version
   */
  @ApiModelProperty(value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public Artifact committed(Boolean committed) {

    this.committed = committed;
    return this;
  }

  /**
   * Get committed
   *
   * @return committed
   */
  @ApiModelProperty(value = "")
  public Boolean getCommitted() {
    return committed;
  }

  public void setCommitted(Boolean committed) {
    this.committed = committed;
  }

  public Artifact storageUrl(String storageUrl) {

    this.storageUrl = storageUrl;
    return this;
  }

  /**
   * Get storageUrl
   *
   * @return storageUrl
   */
  @ApiModelProperty(value = "")
  public String getStorageUrl() {
    return storageUrl;
  }

  public void setStorageUrl(String storageUrl) {
    this.storageUrl = storageUrl;
  }

  public Artifact contentLength(Integer contentLength) {

    this.contentLength = contentLength;
    return this;
  }

  /**
   * Get contentLength
   *
   * @return contentLength
   */
  @ApiModelProperty(value = "")
  public Integer getContentLength() {
    return contentLength;
  }

  public void setContentLength(Integer contentLength) {
    this.contentLength = contentLength;
  }

  public Artifact contentDigest(String contentDigest) {

    this.contentDigest = contentDigest;
    return this;
  }

  /**
   * Get contentDigest
   *
   * @return contentDigest
   */
  @ApiModelProperty(value = "")
  public String getContentDigest() {
    return contentDigest;
  }

  public void setContentDigest(String contentDigest) {
    this.contentDigest = contentDigest;
  }

  public Artifact collectionDate(Long collectionDate) {

    this.collectionDate = collectionDate;
    return this;
  }

  /**
   * Get collectionDate
   *
   * @return collectionDate
   */
  @ApiModelProperty(value = "")
  public Long getCollectionDate() {
    return collectionDate;
  }

  public void setCollectionDate(Long collectionDate) {
    this.collectionDate = collectionDate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Artifact artifact = (Artifact) o;
    return Objects.equals(this.id, artifact.id)
        && Objects.equals(this.collection, artifact.collection)
        && Objects.equals(this.auid, artifact.auid)
        && Objects.equals(this.uri, artifact.uri)
        && Objects.equals(this.version, artifact.version)
        && Objects.equals(this.committed, artifact.committed)
        && Objects.equals(this.storageUrl, artifact.storageUrl)
        && Objects.equals(this.contentLength, artifact.contentLength)
        && Objects.equals(this.contentDigest, artifact.contentDigest)
        && Objects.equals(this.collectionDate, artifact.collectionDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        id,
        collection,
        auid,
        uri,
        version,
        committed,
        storageUrl,
        contentLength,
        contentDigest,
        collectionDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Artifact {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    collection: ").append(toIndentedString(collection)).append("\n");
    sb.append("    auid: ").append(toIndentedString(auid)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    committed: ").append(toIndentedString(committed)).append("\n");
    sb.append("    storageUrl: ").append(toIndentedString(storageUrl)).append("\n");
    sb.append("    contentLength: ").append(toIndentedString(contentLength)).append("\n");
    sb.append("    contentDigest: ").append(toIndentedString(contentDigest)).append("\n");
    sb.append("    collectionDate: ").append(toIndentedString(collectionDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
