#!/bin/sh

# outputs -XmxNNN to set Java max heap size based on physical memory size

sysctl -n hw.physmem | awk '{ \
physmem = $1 ; \
physmb = physmem / (1024 * 1024) ; \
max = 1536 ; \
if (physmb < 128) spare = 0; \
 else if (physmb < 256) spare = 32; \
 else if (physmb < 384) spare = 64; \
 else if (physmb < 512) spare = 96; \
 else spare = 128 ; \
heap = physmb - spare ; \
if ( heap > max ) heap = max; \
print "-Xmx" int(heap) "m" }'
