/*
 * LOCKSS Repository Service REST API
 * REST API of the LOCKSS Repository Service
 *
 * OpenAPI spec version: 2.0.0
 * Contact: lockss-support@lockss.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.lockss.rs.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The status information of the service
 */
@Schema(description = "The status information of the service")
public class ApiStatus {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("componentName")
  private String componentName = null;

  @SerializedName("componentVersion")
  private String componentVersion = null;

  @SerializedName("lockssVersion")
  private String lockssVersion = null;

  @SerializedName("ready")
  private Boolean ready = null;

  @SerializedName("serviceName")
  private String serviceName = null;

  public ApiStatus apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * The version of the API
   * @return apiVersion
  **/
  @Schema(required = true, description = "The version of the API")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public ApiStatus componentName(String componentName) {
    this.componentName = componentName;
    return this;
  }

   /**
   * The name of the component
   * @return componentName
  **/
  @Schema(required = true, description = "The name of the component")
  public String getComponentName() {
    return componentName;
  }

  public void setComponentName(String componentName) {
    this.componentName = componentName;
  }

  public ApiStatus componentVersion(String componentVersion) {
    this.componentVersion = componentVersion;
    return this;
  }

   /**
   * The version of the component software
   * @return componentVersion
  **/
  @Schema(required = true, description = "The version of the component software")
  public String getComponentVersion() {
    return componentVersion;
  }

  public void setComponentVersion(String componentVersion) {
    this.componentVersion = componentVersion;
  }

  public ApiStatus lockssVersion(String lockssVersion) {
    this.lockssVersion = lockssVersion;
    return this;
  }

   /**
   * The version of the LOCKSS system
   * @return lockssVersion
  **/
  @Schema(required = true, description = "The version of the LOCKSS system")
  public String getLockssVersion() {
    return lockssVersion;
  }

  public void setLockssVersion(String lockssVersion) {
    this.lockssVersion = lockssVersion;
  }

  public ApiStatus ready(Boolean ready) {
    this.ready = ready;
    return this;
  }

   /**
   * The indication of whether the service is available
   * @return ready
  **/
  @Schema(required = true, description = "The indication of whether the service is available")
  public Boolean isReady() {
    return ready;
  }

  public void setReady(Boolean ready) {
    this.ready = ready;
  }

  public ApiStatus serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

   /**
   * The name of the service
   * @return serviceName
  **/
  @Schema(required = true, description = "The name of the service")
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiStatus apiStatus = (ApiStatus) o;
    return Objects.equals(this.apiVersion, apiStatus.apiVersion) &&
        Objects.equals(this.componentName, apiStatus.componentName) &&
        Objects.equals(this.componentVersion, apiStatus.componentVersion) &&
        Objects.equals(this.lockssVersion, apiStatus.lockssVersion) &&
        Objects.equals(this.ready, apiStatus.ready) &&
        Objects.equals(this.serviceName, apiStatus.serviceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, componentName, componentVersion, lockssVersion, ready, serviceName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiStatus {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    componentName: ").append(toIndentedString(componentName)).append("\n");
    sb.append("    componentVersion: ").append(toIndentedString(componentVersion)).append("\n");
    sb.append("    lockssVersion: ").append(toIndentedString(lockssVersion)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
