/*
 * LOCKSS Repository Service REST API
 * REST API of the LOCKSS Repository Service
 *
 * OpenAPI spec version: 2.0.0
 * Contact: lockss-support@lockss.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.lockss.rs.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.lockss.rs.model.StorageInfo;
/**
 * Information about the repository
 */
@Schema(description = "Information about the repository")
public class RepositoryInfo {
  @SerializedName("storeInfo")
  private StorageInfo storeInfo = null;

  @SerializedName("indexInfo")
  private StorageInfo indexInfo = null;

  public RepositoryInfo storeInfo(StorageInfo storeInfo) {
    this.storeInfo = storeInfo;
    return this;
  }

   /**
   * Get storeInfo
   * @return storeInfo
  **/
  @Schema(required = true, description = "")
  public StorageInfo getStoreInfo() {
    return storeInfo;
  }

  public void setStoreInfo(StorageInfo storeInfo) {
    this.storeInfo = storeInfo;
  }

  public RepositoryInfo indexInfo(StorageInfo indexInfo) {
    this.indexInfo = indexInfo;
    return this;
  }

   /**
   * Get indexInfo
   * @return indexInfo
  **/
  @Schema(required = true, description = "")
  public StorageInfo getIndexInfo() {
    return indexInfo;
  }

  public void setIndexInfo(StorageInfo indexInfo) {
    this.indexInfo = indexInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryInfo repositoryInfo = (RepositoryInfo) o;
    return Objects.equals(this.storeInfo, repositoryInfo.storeInfo) &&
        Objects.equals(this.indexInfo, repositoryInfo.indexInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storeInfo, indexInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryInfo {\n");
    
    sb.append("    storeInfo: ").append(toIndentedString(storeInfo)).append("\n");
    sb.append("    indexInfo: ").append(toIndentedString(indexInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
