#! /bin/sh

# PROJECT_DIR
PROJECT_DIR=`( cd ../../..; pwd )`
export PROJECT_DIR

if [ "$1" == "clean" ] ; then
  rm -rf lib
  rm -rf test?/V3_*
  rm -rf test?/root_*
fi

if [ "$1" == "start" ] ; then
    mkdir -p lib
    cp ${PROJECT_DIR}/lib/lockss.jar lib
    cp ${PROJECT_DIR}/lib/lockss-test.jar lib
    cp ${PROJECT_DIR}/lib/lockss-plugins.jar lib
fi

for i in 1 2 3 4 5; do
    cd test$i
    if [ "$1" == "start" ] ; then
        if [ -f dpid ] ; then
	    echo daemon already running in `pwd`
	else
            ( ../rundaemon ; rm -f dpid ) &
	    echo started in `pwd`
	fi
    elif [ "$1" == "clean" ] ; then
        if [ -f dpid ] ; then
	    echo cannot clean while daemon is running in `pwd`
	else
            rm -rf config
            rm -rf cache
            rm -rf history
            rm -rf V3-small
            rm -rf V3-large
            rm -rf V3-medium
            rm -rf localA
            rm -rf v3state
            rm -rf plugins
            rm -rf iddb
            rm -rf lib
            rm -f test.out
	fi
    else
        if [ -f dpid ] ; then
	    kill `cat dpid` && rm -f dpid
            echo stopped in `pwd`
	else
	    echo daemon not running in `pwd`
        fi
    fi
    cd ..
done
