#!/bin/sh

usage() {
  echo "usage: $0 [-d diff-args] [-a args] [-1 args1] [-2 args2] <url1> <url2>"
  echo "  Runs ConfigDump to load two prop files (txt or xml), compares them"
  echo "  and outputs any differences in the resulting Configuration.  Exits
  echo "  with zero status if same.  URLs can be either URL or filename."
  echo "  -a passes same args to both invocations of ConfigDump, -1 and -2
  echo "  pass args1 and args2 to ConfigDump when fetching url1 and url2,"
  echo "  respectively.  E.g.,"
  echo "   $0 -a \"-g dev\" http://props.lockss.org:8001/lockss.xml http://..."
  exit 2
}

[ "$#" -lt "2" ] && usage

args1=""
args2=""

while true ; do
  case "$1" in
    -1.? )
      jver="$1"
      shift; continue;;
    "-1" )
      args1="$2"
      shift; shift; continue;;
    "-2" )
      args2="$2"
      shift; shift; continue;;
    "-a" )
      args1="$2"
      args2="$2"
      shift; shift; continue;;
    "-d" )
      diffargs="$2"
      shift; shift; continue;;
    "-*" )
      usage
      exit 2
  esac
  break;
done

f1="$1"
f2="$2"
shift; shift;
TEMP_PREFIX=/tmp/props
t1=`mktemp ${TEMP_PREFIX}.XXXXXX`
t2=`mktemp ${TEMP_PREFIX}.XXXXXX`

test/scripts/run-class $jver ConfigDump -t $args1 -o $t1 "$f1" || exit 1
test/scripts/run-class $jver ConfigDump -t $args2 -o $t2 "$f2" || exit 1

lbl1="$f1"
[ -n "$args1" ] && lbl1="$lbl1 $args1"
lbl2="$f2"
[ -n "$args2" ] && lbl2="$lbl2 $args2"

if diff $diffargs -U 0 -L "$lbl1" -L "$lbl2" $t1 $t2; then
 exit=0
else
 exit=1
fi
rm $t1 $t2
exit $exit
