#!/usr/bin/env python3

__copyright__ = '''\
Copyright (c) 2000-2020, Board of Trustees of Leland Stanford Jr. University
All rights reserved.
'''

__license__ = '''\
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors
may be used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
'''

__version__ = '0.3.1'

import argparse
from datetime import date
import getpass
import os
import shlex
import subprocess
import sys

# DN defaults
_DEFAULT_DN_O = 'Stanford University'
_DEFAULT_DN_OU = 'LOCKSS Program'
_DEFAULT_DN_L = 'Stanford'
_DEFAULT_DN_S = 'California'
_DEFAULT_DN_C = 'US'

# Other constants
_DEFAULT_STORE_PASS = 'password'
_keytool = os.path.join(os.environ['JAVA_HOME'], 'bin', 'keytool') if 'JAVA_HOME' in os.environ else 'keytool'
_ten_years_from_now_in_days = (date(date.today().year + 10, date.today().month, date.today().day) - date.today()).days

class __GenKeyOptions(object):

    @staticmethod
    def make_parser():
        parser = argparse.ArgumentParser(description='LOCKSS signing key generator')
        parser.add_argument('--version', '-V', action='version', version=__version__)
        parser.add_argument('--copyright', '-C', action='store_true', help='show copyright and exit')
        parser.add_argument('--license', '-L', action='store_true', help='show license and exit')
        parser.add_argument('--verbose', '-v', action='store_true', help='output keytool commands')
        # Group: Name
        group = parser.add_argument_group('Name')
        group.add_argument('--full-name', '-f', metavar='FULLNAME', help='full name (default: prompt)')
        group.add_argument('--alias', '-a', metavar='ALIAS', help='alias (default: prompt)')
        # Group: Organization
        group = parser.add_argument_group('Organization')
        group.add_argument('--organization', '-o', metavar='ORG', default=_DEFAULT_DN_O, help='organization (default: %(default)s)')
        group.add_argument('--unit', '-u', metavar='UNIT', default=_DEFAULT_DN_OU, help='organizational unit (default: %(default)s)')
        # Group: Location
        group = parser.add_argument_group('Location')
        group.add_argument('--locality', '-l', metavar='CITY', default=_DEFAULT_DN_L, help='locality (default: %(default)s)')
        group.add_argument('--state', '-s', metavar='STATE', default=_DEFAULT_DN_S, help='state or province (default: %(default)s)')
        group.add_argument('--country', '-c', metavar='XX', default=_DEFAULT_DN_C, help='2-letter ISO 3166 country code (default: %(default)s)')
        # Group: Import
        group = parser.add_argument_group('Import')
        group.add_argument('--import-certificate', '-i', action='store_true', default=None, help='import generated certificate into a keystore (default: prompt)')
        group.add_argument('--no-import-certificate', action='store_false', dest='import_certificate', default=None, help='do not import generated certificate into a keystore')
        group.add_argument('--import-destination', metavar='KEYSTORE', help='destination keystore for import (default: prompt)')
        # Group: Deprecated
        group = parser.add_argument_group('Deprecated', 'These deprecated arguments are kept for backward compatibility and may be removed in a future version.')
        group.add_argument('--full_name', metavar='FULLNAME', dest='full_name', help='deprecated; use --full-name')
        group.add_argument('--name', '-n', metavar='UNIT', dest='unit', default=_DEFAULT_DN_OU, help='deprecated; use --unit')
        # Return parser
        return parser

    def __init__(self, parser, parsed):
        super().__init__()
        # --copyright, --license (--help, --version already taken care of)
        if any([parsed.copyright, parsed.license]):
            if parsed.copyright: print(__copyright__)
            elif parsed.license: print(__license__)
            else: raise RuntimeError('internal error')
            sys.exit()
        # --verbose
        self.verbose = parsed.verbose
        # --organization, --unit, --locality, --state, --country
        self.organization = parsed.organization
        self.unit = parsed.unit
        self.locality = parsed.locality
        self.state = parsed.state
        self.country = parsed.country
        # --import-certificate/--no-import-certificate, --import-destination
        self.import_certificate = parsed.import_certificate
        self.import_destination = parsed.import_destination
        # --full-name, --alias
        self.full_name = parsed.full_name
        while self.full_name is None or len(self.full_name) == 0:
            try:
                self.full_name = input('Full name (e.g. Firstname Lastname): ')
            except (EOFError, KeyboardInterrupt):
                sys.exit()
        self.alias = parsed.full_name
        while self.alias is None or len(self.alias) == 0:
            try:
                self.alias = input('Alias (e.g. flastname-lockss): ')
            except (EOFError, KeyboardInterrupt):
                sys.exit()
        # Passphrase
        self.passphrase = None
        while self.passphrase is None:
            try:
                _p1 = getpass.getpass('Passphrase: ')
            except (EOFError, KeyboardInterrupt):
                sys.exit()
            if len(_p1) < 6:
                print('Passphrase must have at least 6 characters')
                continue
            _p2 = getpass.getpass('Confirm passphrase: ')
            if _p1 != _p2:
                print('Passphrases do not match')
                continue
            self.passphrase = _p1

def __display_certificate(options):
    cmd = [_keytool,
           '-printcert',
           '-file', '{}.cer'.format(options.alias)]
    __run(options, cmd, output=True)

def __export_certificate(options):
    cmd = [_keytool,
           '-exportcert',
           '-file', '{}.cer'.format(options.alias),
           '-keystore', '{}.keystore'.format(options.alias),
           '-alias', options.alias,
           '-storepass', options.passphrase]
    __run(options, cmd)

def __generate_key(options):
    cmd = [_keytool,
           '-genkeypair',
           '-alias', options.alias,
           '-validity', str((date(date.today().year + 10, date.today().month, date.today().day) - date.today()).days),
           '-keystore', '{}.keystore'.format(options.alias),
           '-storepass', options.passphrase,
           '-keypass', options.passphrase,
           '-dname', ', '.join(['{}={}'.format(k, v) for k, v in [('CN', options.full_name),
                                                                  ('O', options.organization),
                                                                  ('OU', options.unit),
                                                                  ('L', options.locality),
                                                                  ('S', options.state),
                                                                  ('C', options.country)] if v is not None and len(v) > 0])]
    __run(options, cmd)

def __import_certificate(options):
    if options.import_certificate is None:
        try:
            _r = input('Import certificate into LOCKSS public keystore? (Y/N) [N]: ')
            options.import_certificate = _r is not None and _r.lower() == 'y' 
        except (EOFError, KeyboardInterrupt):
            sys.exit()
    if options.import_certificate is False:
        return

    if options.import_destination is None:
        try:
            options.import_destination = input('LOCKSS Keystore location [./lockss.keystore]: ')
        except (EOFError, KeyboardInterrupt):
            sys.exit()
        if options.import_destination is None or len(options.import_destination) == 0:
            options.import_destination = './lockss.keystore'

    try:
        _p3 = getpass.getpass('LOCKSS Keystore password [password]: ')
    except (EOFError, KeyboardInterrupt):
        sys.exit()
    if _p3 is None or len(_p3) == 0:
        _p3 = 'password'
    
    cmd = [_keytool,
           '-importcert',
           '-keystore', options.import_destination,
           '-alias', options.alias,
           '-file', '{}.cer'.format(options.alias),
           '-storepass', _p3]
    __run(options, cmd, True)

def __run(options, cmd, output=False):
    if options.verbose:
        print('Executing: {}'.format(shlex.join(cmd)))
        output=True
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
    while proc.poll() is None:
        out = proc.stdout.read(1)
        if len(out) == 0:
            continue
        if output:
            print(out, end='', flush=True)
    proc.wait()
    if proc.returncode != 0:
        print('{} exited with {}'.format(cmd[0], proc.returncode))
        sys.exit(proc.returncode)

def __main():
    '''Main method.'''
    parser = __GenKeyOptions.make_parser()
    options = __GenKeyOptions(parser, parser.parse_args())
    __generate_key(options)
    __export_certificate(options)
    __display_certificate(options)
    __import_certificate(options)

if __name__ == '__main__': __main()

