#!/bin/sh

if [ "$#" = "0" ]; then
 echo "Usage: $0 <class-name>"
 echo "Runs <class-name> in junit under jdb."
 echo "Must be run from project base dir."
 exit 1
fi

PROJECT_DIR=.

CLASSPATH=`cat test/test-classpath`
export CLASSPATH

while true ; do
  case "$1" in
    "-classpath" )
      if [ -z "$CLASSPATH" ] ; then
	CLASSPATH="$2"
      else
	CLASSPATH="$CLASSPATH":"$2"
      fi
      echo "CLASSPATH=$CLASSPATH"
      shift; shift; continue;;
    "-1.4" )
      if [ -z "$JAVA_14_HOME" ] ; then
	echo "-1.4 option requires JAVA_14_HOME to point to 1.4 install dir"
	exit 1;
      fi
      JAVA_HOME="${JAVA_14_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
  esac
  break;
done

class=$1
shift

jdb junit.textui.TestRunner -Dxorg.lockss.defaultLogLevel=warning $class
