#!/bin/sh

stdout="rpt-test-out"
stderr="rpt-test-err"

usage() {
 echo "Usage: $0 [-q] [-Dprop=val] <rpt-count> <class-name>"
 echo "Runs <class-name> in junit <rpt-count> times,"
 echo " sending stdout and stderr to $stdout and $stderr."
 echo "-q  suppresses printing a dot for each iteration."
 echo "Other -flags are passed in to the jvm unmodified."
 echo "Must be run from project base dir."
 exit 1
}

if [ "$#" = "0" ]; then
  usage;
fi

showdots=1

while true ; do
  case "$1" in
    "-q" )
      showdots=0
      shift; continue;;
    "-1.4" )
      if [ -z "$JAVA_14_HOME" ] ; then
	echo "-1.4 option requires JAVA_14_HOME to point to 1.4 install dir"
	exit 1;
      fi
      JAVA_HOME="${JAVA_14_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
    "-1.5" )
      if [ -z "$JAVA_15_HOME" ] ; then
	echo "-1.5 option requires JAVA_15_HOME to point to 1.5 install dir"
	exit 1;
      fi
      JAVA_HOME="${JAVA_15_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
    -* )
      if [ -z "$jvmargs" ] ; then
	jvmargs="$1"
      else
	jvmargs="$jvmargs $1"
      fi
      shift; continue;;
  esac
  break;
done

[ "$#" -ne "2" ] && usage

PROJECT_DIR=.

rpt=$1
class=$2
shift
shift

# local copy of lockss jars allows recompile while we're running
tmplib=tmplib
mkdir -p $tmplib
cp ${PROJECT_DIR}/lib/lockss.jar $tmplib
cp ${PROJECT_DIR}/lib/lockss-test.jar $tmplib
CLASSPATH=$tmplib/lockss.jar:$tmplib/lockss-test.jar:`cat test/test-classpath`
export CLASSPATH

failcnt=0

msg="Starting $rpt iterations at `date`"
echo "$msg" >> $stderr
echo "$msg" >> $stdout

ix=1
while [ $ix -le $rpt ]; do
  echo "** iter $ix" >> $stderr
  echo "** iter $ix" >> $stdout

  if ! java $jvmargs junit.textui.TestRunner $class >>$stdout 2>>$stderr; then
    failcnt=$((failcnt + 1))
    [ $showdots = 1 ] && echo -n F
  else
    [ $showdots = 1 ] && echo -n .
  fi
  ix=$(($ix + 1))
done
echo
echo $failcnt failures
