#!/bin/bash

# Copyright (c) 2000-2022, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

if [ "$#" == "0" ]; then
 echo "Usage: $0 <java-args> <class-name> <args>"
 echo "Runs <class-name> "
 echo "Must be run from project base dir."
 exit 1
fi

PROJECT_DIR=.

CLASSPATH=`cat test/test-classpath`
export CLASSPATH

if command -v realpath > /dev/null ; then
  REALPATH='realpath'
elif command -v grealpath > /dev/null ; then
  REALPATH='grealpath'
elif command -v readlink > /dev/null ; then
  REALPATH='readlink -f'
else
  echo "${0}: no realpath executable on the PATH" >&2
  exit 1
fi

args=""
quiet=""

while true ; do
  case "$1" in
    "-q"|"-quiet" )
      quiet=1  
      shift; continue;;
    "-classpath" )
      if [ -z "$CLASSPATH" ] ; then
	CLASSPATH="$2"
      else
	CLASSPATH="$CLASSPATH":"$2"
      fi
      [ -z "$quiet" ] && echo "CLASSPATH=$CLASSPATH"
      shift; shift; continue;;
    "-1.7" )
      if [ -z "$JAVA_17_HOME" ] ; then
	echo "-1.7 option requires JAVA_17_HOME to point to 1.7 install dir" >&2
	exit 1;
      fi
      JAVA_HOME="${JAVA_17_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      [ -z "$quiet" ] && echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
    "-1.8" )
      if [ -z "$JAVA_18_HOME" ] ; then
	echo "-1.8 option requires JAVA_18_HOME to point to 1.8 install dir" >&2
	exit 1;
      fi
      JAVA_HOME="${JAVA_18_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      [ -z "$quiet" ] && echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
    "-plugins")
      for f in lib/lockss-plugins.jar lib/lockss-plugins-test.jar ; do
        if [ -n "$CLASSPATH" ] ; then
          CLASSPATH="${CLASSPATH}:"
        fi
        CLASSPATH="${CLASSPATH}$($REALPATH $f)"
      done
      [ -z "$quiet" ] && echo "CLASSPATH=$CLASSPATH"
      shift; continue;;
    "-*" )
      args="$args $1"
      shift; continue;;
  esac
  break;
done

class=$1
shift

java $args $class "$@"
