#!/bin/bash

if [ "$#" == "0" ]; then
 echo "Usage: $0 <java-args> <class-name> <args>"
 echo "Runs <class-name> "
 echo "Must be run from project base dir."
 exit 1
fi

PROJECT_DIR=.

CLASSPATH=`cat test/test-classpath`
export CLASSPATH

args=""
quiet=""

while true ; do
  case "$1" in
    "-q"|"-quiet" )
      quiet=1  
      shift; continue;;
    "-classpath" )
      if [ -z "$CLASSPATH" ] ; then
	CLASSPATH="$2"
      else
	CLASSPATH="$CLASSPATH":"$2"
      fi
      [ -z "$quiet" ] && echo "CLASSPATH=$CLASSPATH"
      shift; shift; continue;;
    "-1.7" )
      if [ -z "$JAVA_17_HOME" ] ; then
	echo "-1.7 option requires JAVA_17_HOME to point to 1.7 install dir" >&2
	exit 1;
      fi
      JAVA_HOME="${JAVA_17_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      [ -z "$quiet" ] && echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
    "-1.8" )
      if [ -z "$JAVA_18_HOME" ] ; then
	echo "-1.8 option requires JAVA_18_HOME to point to 1.8 install dir" >&2
	exit 1;
      fi
      JAVA_HOME="${JAVA_18_HOME}"
      export JAVA_HOME
      PATH="$JAVA_HOME/bin:$PATH"
      export PATH
      [ -z "$quiet" ] && echo JAVA_HOME="$JAVA_HOME"
      shift; continue;;
    "-plugins")
      for f in lib/lockss-plugins.jar lib/lockss-plugins-test.jar ; do
        if [ -n "$CLASSPATH" ] ; then
          CLASSPATH="${CLASSPATH}:"
        fi
        CLASSPATH="${CLASSPATH}$(realpath $f)"
      done
      [ -z "$quiet" ] && echo "CLASSPATH=$CLASSPATH"
      shift; continue;;
    "-*" )
      args="$args $1"
      shift; continue;;
  esac
  break;
done

class=$1
shift

java $args $class "$@"
