#!/bin/sh

cdproj()
{
 while :
  do
    [ -f test/scripts/run-class ] && break;
    [ `pwd` = '/' ] && echo "Must be run in or under project directory" && exit 1;
    cd ..
  done
}

cdproj

test/scripts/run-class -Dorg.lockss.defaultLogLevel=critical TitleParams -c test/frameworks/common.txt -o $1
