#!/bin/bash
#
# Simple wrapper script to send notification e-mail when process is complete.
# Add this variable to .profile with your email address
# export PYLORUS_MAIL="myemail@stanford.edu"

# Use sleep command for debug.
./pylorus.py $*
# sleep 5

# Use mailx to send a notification.
if [ "x$PYLORUS_MAIL" != "x" ]
then 
`echo "$USER: Job: $* on $HOSTNAME at $PWD" | mailx -s "Job Complete" ${PYLORUS_MAIL}`
fi
exit 0

