#!/bin/bash
#
# Simple wrapper script to send notification e-mail when process is complete.
# Add this variable to .profile with your email address
# export PYLORUS_MAIL="myemail@stanford.edu"

# Use sleep command for debug.
$(dirname "$0")/pylorus.py $*
#sleep 5

# Use mailx to send a notification.
folder=`echo $PWD | sed 's/.*\///'`
if [ "x$PYLORUS_MAIL" != "x" ]
then 
echo "$USER: Job: $* on $HOSTNAME at $PWD" | mailx -s "Job Complete $folder" ${PYLORUS_MAIL}
fi
exit 0

