/*
 * LOCKSS Configuration Service REST API
 * REST API of the LOCKSS Configuration Service
 *
 * OpenAPI spec version: 2.0.0
 * Contact: lockss-support@lockss.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.lockss.laaws.model.cfg;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The status information of the service
 */
@Schema(description = "The status information of the service")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-17T15:05:28.577-07:00[America/Los_Angeles]")
public class ApiStatus {
  @SerializedName("version")
  private String version = null;

  @SerializedName("ready")
  private Boolean ready = null;

  public ApiStatus version(String version) {
    this.version = version;
    return this;
  }

   /**
   * The version of the service
   * @return version
  **/
  @Schema(required = true, description = "The version of the service")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public ApiStatus ready(Boolean ready) {
    this.ready = ready;
    return this;
  }

   /**
   * The indication of whether the service is available
   * @return ready
  **/
  @Schema(required = true, description = "The indication of whether the service is available")
  public Boolean isReady() {
    return ready;
  }

  public void setReady(Boolean ready) {
    this.ready = ready;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiStatus apiStatus = (ApiStatus) o;
    return Objects.equals(this.version, apiStatus.version) &&
        Objects.equals(this.ready, apiStatus.ready);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, ready);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiStatus {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
