/*
 * LOCKSS Configuration Service REST API
 * REST API of the LOCKSS Configuration Service
 *
 * OpenAPI spec version: 2.0.0
 * Contact: lockss-support@lockss.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.lockss.laaws.model.cfg;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The encapsulation of the result of adding an Archival Unit
 */
@Schema(description = "The encapsulation of the result of adding an Archival Unit")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-17T15:05:28.577-07:00[America/Los_Angeles]")
public class ContentConfigurationResult {
  @SerializedName("auId")
  private String auId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("isSuccess")
  private Boolean isSuccess = null;

  @SerializedName("message")
  private String message = null;

  public ContentConfigurationResult auId(String auId) {
    this.auId = auId;
    return this;
  }

   /**
   * The identifier of the Archival Unit
   * @return auId
  **/
  @Schema(required = true, description = "The identifier of the Archival Unit")
  public String getAuId() {
    return auId;
  }

  public void setAuId(String auId) {
    this.auId = auId;
  }

  public ContentConfigurationResult name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the Archival Unit
   * @return name
  **/
  @Schema(required = true, description = "The name of the Archival Unit")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ContentConfigurationResult isSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
    return this;
  }

   /**
   * An indication of whether the AU was successfully added or\\ \\ not
   * @return isSuccess
  **/
  @Schema(required = true, description = "An indication of whether the AU was successfully added or\\ \\ not")
  public Boolean isIsSuccess() {
    return isSuccess;
  }

  public void setIsSuccess(Boolean isSuccess) {
    this.isSuccess = isSuccess;
  }

  public ContentConfigurationResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * A descriptive message regarding the result of the operation
   * @return message
  **/
  @Schema(required = true, description = "A descriptive message regarding the result of the operation")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentConfigurationResult contentConfigurationResult = (ContentConfigurationResult) o;
    return Objects.equals(this.auId, contentConfigurationResult.auId) &&
        Objects.equals(this.name, contentConfigurationResult.name) &&
        Objects.equals(this.isSuccess, contentConfigurationResult.isSuccess) &&
        Objects.equals(this.message, contentConfigurationResult.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auId, name, isSuccess, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentConfigurationResult {\n");
    
    sb.append("    auId: ").append(toIndentedString(auId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isSuccess: ").append(toIndentedString(isSuccess)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
