/*
 * LOCKSS Configuration Service REST API
 * REST API of the LOCKSS Configuration Service
 *
 * OpenAPI spec version: 2.0.0
 * Contact: lockss-support@lockss.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.lockss.laaws.model.cfg;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The result of an archival unit generic control request
 */
@Schema(description = "The result of an archival unit generic control request")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-17T15:05:28.577-07:00[America/Los_Angeles]")
public class RequestAuControlResult {
  @SerializedName("id")
  private String id = null;

  @SerializedName("success")
  private Boolean success = null;

  @SerializedName("errorMessage")
  private String errorMessage = null;

  public RequestAuControlResult id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier of the archival unit
   * @return id
  **/
  @Schema(required = true, description = "The identifier of the archival unit")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RequestAuControlResult success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * An indication of whether the result is successful
   * @return success
  **/
  @Schema(required = true, description = "An indication of whether the result is successful")
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public RequestAuControlResult errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * The error message as a result of the operation
   * @return errorMessage
  **/
  @Schema(required = true, description = "The error message as a result of the operation")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestAuControlResult requestAuControlResult = (RequestAuControlResult) o;
    return Objects.equals(this.id, requestAuControlResult.id) &&
        Objects.equals(this.success, requestAuControlResult.success) &&
        Objects.equals(this.errorMessage, requestAuControlResult.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, success, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestAuControlResult {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
