/*
 * $Id$
 */

/*

Copyright (c) 2000-2007 Board of Trustees of Leland Stanford Jr. University,
all rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
STANFORD UNIVERSITY BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Except as contained in this notice, the name of Stanford University shall not
be used in advertising or otherwise to promote the sale, use or other dealings
in this Software without prior written authorization from Stanford University.

*/

package org.lockss.plugin.springer.link;

import java.io.*;
import java.util.*;

import org.lockss.filter.pdf.*;
import org.lockss.filter.pdf.PageTransformUtil.ExtractStringsToOutputStream;
import org.lockss.plugin.*;
import org.lockss.plugin.highwire.AmericanMedicalAssociationPdfTransform.NormalizeCurrentAsOf;
import org.lockss.plugin.highwire.HighWirePdfFilterFactory.CollapseDownloadedFrom;
import org.lockss.util.*;
import org.pdfbox.cos.*;
import org.pdfbox.pdmodel.*;
import org.pdfbox.pdmodel.common.PDRectangle;
import org.pdfbox.pdmodel.interactive.action.type.*;
import org.pdfbox.pdmodel.interactive.annotation.*;
import org.pdfbox.util.operator.OperatorProcessor;

public class SpringerLinkPdfFilterFactory implements FilterFactory {

  /**
   * <p>Bypasses {@link TextScrapingDocumentTransform}, which fails on
   * zero-length results. To be fixed in the PDF framework later.</p>
   * @see TextScrapingDocumentTransform
   */
  public class ResilientTextScrapingDocumentTransform extends OutputStreamDocumentTransform {
	    public DocumentTransform makePreliminaryTransform() throws IOException {
	        return new NormalizeMetadata();
	      }
    public DocumentTransform makeTransform() throws IOException {
      return new ConditionalDocumentTransform(makePreliminaryTransform(),
                                              false, // Difference with TextScrapingDocumentTransform
                                              new TransformEachPage(new ExtractStringsToOutputStream(outputStream) {
                                                @Override
                                                public void processStream(PDPage arg0, PDResources arg1, COSStream arg2) throws IOException {
                                                  logger.debug3("ResilientTextScrapingDocumentTransform: unconditional signalChange()");
                                                  signalChange(); // Difference with TextScrapingDocumentTransform
                                                  super.processStream(arg0, arg1, arg2);
                                                }
                                              }));
    }
  }


  public static class EraseMetadataSection implements DocumentTransform {

    public boolean transform(PdfDocument pdfDocument) throws IOException {
      pdfDocument.setMetadata(" ");
      return true;
    }

  }


  public static class NormalizeMetadata extends AggregateDocumentTransform {

    public NormalizeMetadata() {
      super(// Remove the modification date
            new RemoveModificationDate(),
            // Remove the text in the metadata section
            new EraseMetadataSection(),
            // Remove the variable part of the document ID
            new NormalizeTrailerId());
    }

  }

  public static class NormalizeTrailerId implements DocumentTransform {

    public boolean transform(PdfDocument pdfDocument) throws IOException {
      COSDictionary trailer = pdfDocument.getTrailer();
      if (trailer != null) {
        // Put bogus ID to prevent autogenerated (variable) ID
        COSArray id = new COSArray();
        id.add(new COSString("12345678901234567890123456789012"));
        id.add(id.get(0));
        trailer.setItem(COSName.getPDFName("ID"), id);
        return true; // success
      }
      return false; // all other cases are unexpected
    }

  }

  public static class RemoveModificationDate implements DocumentTransform {

    public boolean transform(PdfDocument pdfDocument) throws IOException {
      pdfDocument.removeModificationDate();
      return true;
    }

  }

  public InputStream createFilteredInputStream(ArchivalUnit au,
                                               InputStream in,
                                               String encoding) {
    logger.debug2("PDF filter factory for: " + au.getName());
    OutputDocumentTransform documentTransform = new ResilientTextScrapingDocumentTransform();
    if (documentTransform == null) {
      logger.debug2("Unfiltered");
      return in;
    }
    else {
      return PdfUtil.applyFromInputStream(documentTransform, in);
    }
  }

  /**
   * <p>A logger for use by this class.</p>
   */
  private static Logger logger = Logger.getLogger(SpringerLinkPdfFilterFactory.class);

}
